import { Inter } from "next/font/google";
import "./globals.css";

import themes from "../../themes.json";
import ThemeContextProvider from "../contexts/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  console.log("themes", themes);
  const theme = themes[Math.floor(Math.random() * themes.length)];
  console.log("THEME", theme);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeContextProvider serverTheme={theme}>
          {children}
        </ThemeContextProvider>
      </body>
    </html>
  );
}
